##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: ns1
  labels:
    app: ratings
spec:
  type: ClusterIP
  clusterIP: 10.3.82.62
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  namespace: ns1
  labels:
    app: ratings
  annotations:
    ves.io/workload-flavor: medium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings 
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - name: ratings
        image: gcr.io/devtest-293809/examples-bookinfo-ratings-v1:1.8.0
        imagePullPolicy: Always 
        ports:
        - containerPort: 9080
        env:
        - name: SERVICES_DOMAIN
          value: ns2
---
